### ISSUE TITLE
Unable to compile develop branch

### ISSUE THREAD

**Issue by AlexMikhalev** [atomicdata-dev/atomic-server#664]
```
   Compiling parking_lot_core v0.8.5
The following warnings were emitted during compilation:

warning: No JS dist folder found, building...
warning: install js packages...
warning: build js assets...

error: failed to run custom build command for `atomic-server v0.34.5 (/home/alex/rust_code/atomic-server/server)`

Caused by:
  process didn't exit successfully: `/home/alex/rust_code/atomic-server/target/debug/build/atomic-server-6ab0915fd6707ef7/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=../browser
  cargo:warning=No JS dist folder found, building...
  cargo:warning=install js packages...
  cargo:warning=build js assets...

  --- stderr
  thread 'main' panicked at 'js build failed: [vite-plugin-pwa:build] Failed to resolve entry for package "@tomic/react". The package may have incorrect main/module/exports specified in its package.json.
  error during build:
  Error: Failed to resolve entry for package "@tomic/react". The package may have incorrect main/module/exports specified in its package.json.
      at packageEntryFailure (file:///home/alex/rust_code/atomic-server/browser/node_modules/.pnpm/vite@4.4.8_@types+node@16.18.39/node_modules/vite/dist/node/chunks/dep-75f53616.js:28687:11)
      at resolvePackageEntry (file:///home/alex/rust_code/atomic-server/browser/node_modules/.pnpm/vite@4.4.8_@types+node@16.18.39/node_modules/vite/dist/node/chunks/dep-75f53616.js:28684:5)
      at tryNodeResolve (file:///home/alex/rust_code/atomic-server/browser/node_modules/.pnpm/vite@4.4.8_@types+node@16.18.39/node_modules/vite/dist/node/chunks/dep-75f53616.js:28415:20)
      at Object.resolveId (file:///home/alex/rust_code/atomic-server/browser/node_modules/.pnpm/vite@4.4.8_@types+node@16.18.39/node_modules/vite/dist/node/chunks/dep-75f53616.js:28176:28)
      at file:///home/alex/rust_code/atomic-server/browser/node_modules/.pnpm/rollup@3.27.2/node_modules/rollup/dist/es/shared/node-entry.js:25356:40
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async PluginDriver.hookFirstAndGetPlugin (file:///home/alex/rust_code/atomic-server/browser/node_modules/.pnpm/rollup@3.27.2/node_modules/rollup/dist/es/shared/node-entry.js:25256:28)
      at async resolveId (file:///home/alex/rust_code/atomic-server/browser/node_modules/.pnpm/rollup@3.27.2/node_modules/rollup/dist/es/shared/node-entry.js:23931:26)
      at async ModuleLoader.resolveId (file:///home/alex/rust_code/atomic-server/browser/node_modules/.pnpm/rollup@3.27.2/node_modules/rollup/dist/es/shared/node-entry.js:24345:15)
      at async Object.resolveId (file:///home/alex/rust_code/atomic-server/browser/node_modules/.pnpm/vite@4.4.8_@types+node@16.18.39/node_modules/vite/dist/node/chunks/dep-75f53616.js:7910:10)
      at async PluginDriver.hookFirstAndGetPlugin (file:///home/alex/rust_code/atomic-server/browser/node_modules/.pnpm/rollup@3.27.2/node_modules/rollup/dist/es/shared/node-entry.js:25256:28)
      at async resolveId (file:///home/alex/rust_code/atomic-server/browser/node_modules/.pnpm/rollup@3.27.2/node_modules/rollup/dist/es/shared/node-entry.js:23931:26)
      at async ModuleLoader.resolveId (file:///home/alex/rust_code/atomic-server/browser/node_modules/.pnpm/rollup@3.27.2/node_modules/rollup/dist/es/shared/node-entry.js:24345:15)
      at async file:///home/alex/rust_code/atomic-server/browser/node_modules/.pnpm/rollup@3.27.2/node_modules/rollup/dist/es/shared/node-entry.js:24636:50
  ', server/build.rs:99:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

```
cargo --version 
cargo 1.71.0 (cfd3bbd8f 2023-06-08)
git log -1
commit a60a1e28a7615202f21eaac7e98afe868ea38790 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Joep Meindertsma <joep@ontola.io>
Date:   Sat Sep 2 16:56:24 2023 +0200

    Throw error when building if JS is broken

npm --version
8.14.0
pnpm --version 
8.6.7

**Comment by joepio** [comment]
The `pnpm build` command was being run in a subdir. My bad. Fixed it now!
