### ISSUE TITLE
CI test fail - dialog, hover 

### ISSUE THREAD

**Issue by joepio** [atomicdata-dev/atomic-server#716]
The `dialog` test keeps failing because the `.hover` isn't working in the CI.

it is working properly locally.

```
Error: locator.hover: Timeout 5000ms exceeded.
Call log:
  - waiting for getByTestId('searchbox-results').getByText('boolean - Either `true` or `false`')


   at tests/test-utils.ts:219

  217 |
  218 |   return async (name: string) => {
> 219 |     await selector.getByTestId('searchbox-results').getByText(name).hover();
      |                                                                     ^
  220 |     await selector.getByTestId('searchbox-results').getByText(name).click();
  221 |   };
  222 | }

    at selectDatatypeOption (/app/e2e/tests/test-utils.ts:219:69)
    at /app/e2e/tests/e2e.spec.ts:518:11
```
<img width="1091" alt="Screenshot 2023-11-28 at 21 32 42" src="https://github.com/atomicdata-dev/atomic-server/assets/2183313/010d54aa-3370-4e59-9a34-22a5bdbcfebb">

**Comment by joepio** [comment]
This is caused by #708

**Comment by joepio** [comment]
Since #706 is now closed, this is fixed too
